from scm.plams import Molecule, SCMJob, SCMResults

class DFTBResults(SCMResults):
    def get_main_molecule(self) -> Molecule: ...
    def get_input_molecule(self) -> Molecule: ...
    def get_history_molecules(self) -> list[Molecule]: ...
    def get_energy(self, unit: str = ...) -> float: ...
    def get_dipole_vector(self, unit: str = ...) -> list[float]: ...
    def get_gradients(self) -> list[list[float]]: ...

class DFTBJob(SCMJob): ...
