from typing import Iterable, Union, SupportsFloat, List, Any

import numpy as np
import numpy.typing as npt

Vector = Iterable[Union[str, bytes, SupportsFloat]]

def rotation_matrix(vec1: npt.ArrayLike, vec2: npt.ArrayLike) -> np.ndarray: ...
def axis_rotation_matrix(
    vector: npt.ArrayLike, angle: npt.ArrayLike, unit: str = ...
) -> np.ndarray: ...
def distance_array(array1: np.ndarray, array2: np.ndarray) -> np.ndarray: ...
def angle(vec1: Vector, vec2: Vector, result_unit: str = ...) -> np.float_: ...
def dihedral(
    p1: Vector, p2: Vector, p3: Vector, p4: Vector, unit: str = ...
) -> np.float_: ...
def cell_shape(lattice: npt.ArrayLike) -> List[Any]: ...
