from typing import List, Dict, Any, ClassVar, Union

class PeriodicTable:
    data: ClassVar[List[List[Any]]] = ...
    symtonum: ClassVar[Dict[str, int]] = ...
    dummysymbols: ClassVar[List[str]] = ...
    @classmethod
    def get_atomic_number(cls, symbol: str) -> int: ...
    @classmethod
    def get_symbol(cls, atnum: int) -> str: ...
    @classmethod
    def get_mass(cls, arg: Union[str, int]) -> float: ...
    @classmethod
    def get_radius(cls, arg: Union[str, int]) -> float: ...
    @classmethod
    def get_connectors(cls, arg: Union[str, int]) -> int: ...
    @classmethod
    def get_metallic(cls, arg: Union[str, int]) -> int: ...
    @classmethod
    def get_electronegative(cls, arg: Union[str, int]) -> int: ...
    @classmethod
    def set_mass(cls, element: str, value: float) -> None: ...
    @classmethod
    def set_radius(cls, element: str, value: float) -> None: ...
    @classmethod
    def set_connectors(cls, element: str, value: float) -> None: ...

PT = PeriodicTable
