from typing import Any, Optional, List, Generic, Iterable, Tuple, Mapping, Iterator

from .bond import Bond
from .molecule import Molecule
from ..core.settings import Settings

Matrix = Tuple[Tuple[float, float, float],
               Tuple[float, float, float],
               Tuple[float, float, float]]

class Atom(Iterable[float]):
    symbol: str = ...
    atnum: int = ...
    mol: Molecule = ...
    bonds: List[Bond] = ...
    properties: Settings = ...
    coords: Tuple[float, float, float] = ...

    def __init__(self, atnum: int = ..., symbol: Optional[str] = ..., coords: Optional[Tuple[float, float, float]] = ..., unit: str = ..., bonds: Optional[List[Bond]] = ..., mol: Optional[Molecule] = ..., **other: Any) -> None: ...
    def __iter__(self) -> Iterator[float]: ...

    x: float = ...
    y: float = ...
    z: float = ...
    mass: float = ...
    radius: float = ...
    connectors: float = ...
    is_metallic: bool = ...
    is_electronegative: bool = ...

    def translate(self, vector: Iterable[float], unit: str = ...) -> None: ...
    def move_to(self, point: Iterable[float], unit: str = ...) -> None: ...
    def distance_to(self, point: Iterable[float], unit: str = ..., result_unit: str = ...) -> Tuple[float, float, float]: ...
    def vector_to(self, point: Iterable[float], unit: str = ..., result_unit: str = ...) -> float: ...
    def angle(self, poinfloat: Iterable[float], poinfloat: Iterable[float], poinfloatunit: str = ..., poinfloatunit: str = ..., result_unit: str = ...): ...
    def rotate(self, matrix: Union[np.array, Matrix]) -> None: ...
    def neighbors(self) -> List[Atom]: ...
