class PlamsError(Exception): ...
class FileError(PlamsError): ...
class ResultsError(PlamsError): ...
class JobError(PlamsError): ...
class PTError(PlamsError): ...
class UnitsError(PlamsError): ...
class MoleculeError(PlamsError): ...
