import sys
import types
from collections.abc import Callable, Iterable, Mapping, Sequence
from typing import Any, Generic, TypeVar, overload

if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

_MT = TypeVar("_MT", bound=_SupportsMissing)
_ST = TypeVar("_ST", bound=Settings)

class _SupportsMissing(Protocol):
    def __missing__(self, __key: Any) -> Any: ...

class Settings(dict[str, Any]):
    def copy(self: _ST) -> _ST: ...
    def soft_update(self: _ST, other: Mapping[str, Any]) -> _ST: ...
    def update(self, other: Mapping[str, Any]) -> None: ...  # type: ignore[override]
    def merge(self: _ST, other: Mapping[str, Any]) -> _ST: ...
    def find_case(self, key: str) -> str: ...
    def as_dict(self) -> dict[str, Any]: ...
    @classmethod
    def suppress_missing(cls: type[_MT]) -> SuppressMissing[_MT]: ...
    def get_nested(self, key_tuple: Iterable[Any], suppress_missing: bool = False) -> Any: ...
    def set_nested(self, key_tuple: Sequence[Any], value: Any, suppress_missing: bool = False) -> None: ...
    def flatten(self, flatten_list: bool = ...) -> Settings: ...
    def unflatten(self, unflatten_list: bool = ...) -> Settings: ...
    @classmethod  # type: ignore[override]
    @overload
    def fromkeys(cls, __iterable: Iterable[str]) -> Settings: ...
    @classmethod
    @overload
    def fromkeys(cls, __iterable: Iterable[str], __value: Any) -> Settings: ...
    def __missing__(self, __key: str) -> Settings: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __add__(self: _ST, other: Mapping[str, Any]) -> _ST: ...
    def __iadd__(self: _ST, other: Mapping[str, Any]) -> _ST: ...
    def __copy__(self: _ST) -> _ST: ...

class SuppressMissing(Generic[_MT]):
    obj: _MT
    missing: Callable[[Any, _MT, Any], Any]
    def __init__(self, obj: type[_MT]) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self, exc_type: None | type[BaseException], exc_value: None | BaseException, traceback: None | types.TracebackType
    ) -> None: ...
